[build]
builder = "nixpacks"

[deploy]
startCommand = "cd twitter && gunicorn twitter.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"

[environments.production]
variables = { DEBUG = "False" }