[build]
builder = "nixpacks"

[deploy]
startCommand = "python twitter/start.py"
restartPolicyType = "on_failure"

[environments.production]
variables = { DEBUG = "False", CSRF_COOKIE_SECURE = "True", SESSION_COOKIE_SECURE = "True" }